version: "3.8"

services:
  registry:
    image: registry:2
    ports:
      - "5000:5000"
    volumes:
      - registry-data:/var/lib/registry

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

  postgres:
    image: ankane/pgvector
    environment:
      POSTGRES_USER: noa
      POSTGRES_PASSWORD: noa
      POSTGRES_DB: noa
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  supabase:
    image: supabase/postgres
    environment:
      POSTGRES_PASSWORD: supersecret
    ports:
      - "5433:5432"
    volumes:
      - supabase-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  nats:
    image: nats:2
    ports:
      - "4222:4222"

volumes:
  registry-data:
  minio-data:
  postgres-data:
  supabase-data:
